from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ProactiveConfig:
    enabled: bool = False
    interval_seconds: int = 1800
    threshold: float = 0.70
    items_per_source: int = 3
    recent_chat_messages: int = 20
    model: str = ""
    default_channel: str = "telegram"
    default_chat_id: str = ""
    dedupe_seen_ttl_hours: int = 24 * 14
    delivery_dedupe_hours: int = 24
    semantic_dedupe_enabled: bool = True
    semantic_dedupe_threshold: float = 0.90
    semantic_dedupe_window_hours: int = 72
    semantic_dedupe_max_candidates: int = 200
    semantic_dedupe_ngram: int = 3
    semantic_dedupe_text_max_chars: int = 240
    use_global_memory: bool = True
    global_memory_max_chars: int = 3000
    score_weight_energy: float = 0.40
    score_weight_content: float = 0.40
    score_weight_recent: float = 0.20
    score_content_halfsat: float = 3.0
    score_recent_scale: float = 10.0
    score_llm_threshold: float = 0.40
    score_pre_threshold: float = 0.05
    decision_score_random_strength: float = 0.0
    interrupt_weight_reply: float = 0.35
    interrupt_weight_activity: float = 0.25
    interrupt_weight_fatigue: float = 0.15
    interrupt_activity_decay_minutes: float = 180.0
    interrupt_reply_decay_minutes: float = 120.0
    interrupt_no_reply_decay_minutes: float = 360.0
    interrupt_fatigue_window_hours: int = 24
    interrupt_fatigue_soft_cap: float = 6.0
    interrupt_random_strength: float = 0.12
    interrupt_min_floor: float = 0.08
    tick_interval_s0: int = 4800
    tick_interval_s1: int = 2400
    tick_interval_s2: int = 1080
    tick_interval_s3: int = 420
    tick_jitter: float = 0.3
    anyaction_enabled: bool = False
    anyaction_daily_max_actions: int = 24
    anyaction_min_interval_seconds: int = 300
    anyaction_reset_hour_local: int = 12
    anyaction_timezone: str = "Asia/Shanghai"
    anyaction_probability_min: float = 0.03
    anyaction_probability_max: float = 0.45
    anyaction_idle_scale_minutes: float = 240.0
    # 决策模式由 compose_judge_enabled 决定；feature_scoring_enabled 仅保留兼容，不再参与分支选择。
    feature_scoring_enabled: bool = False
    compose_judge_enabled: bool = False
    active_decision_mode: str = "feature"
    inactive_config_keys: list[str] = field(default_factory=list)
    compose_no_content_token: str = "<no_content/>"
    feature_send_threshold: float = 0.52
    feature_weight_topic_continuity: float = 0.16
    feature_weight_interest_match: float = 0.32
    feature_weight_content_novelty: float = 0.20
    feature_weight_reconnect_value: float = 0.16
    feature_weight_message_readiness: float = 0.16
    feature_weight_disturb_risk: float = 0.70
    feature_weight_interrupt_penalty: float = 0.30
    feature_weight_d_recent_bonus: float = 0.10
    feature_weight_d_content_bonus: float = 0.10
    feature_weight_d_energy_bonus: float = 0.08
    memory_retrieval_enabled: bool = True
    memory_top_k_procedure: int = 4
    memory_top_k_history: int = 6
    memory_query_max_recent_messages: int = 3
    memory_query_max_items: int = 3
    memory_history_gate_enabled: bool = True
    memory_scope_fallback_to_global: bool = False
    memory_trace_enabled: bool = True
    message_dedupe_enabled: bool = True
    message_dedupe_recent_n: int = 5
    llm_reject_cooldown_hours: int = 12
    pending_queue_enabled: bool = True
    pending_item_ttl_hours: int = 12
    pending_candidate_limit: int = 3
    pending_max_per_source: int = 20
    pending_max_total: int = 200
    skill_actions_enabled: bool = False
    skill_actions_path: str = ""
    fitbit_enabled: bool = False
    fitbit_url: str = "http://127.0.0.1:18765"
    fitbit_poll_seconds: int = 300
    sleep_modifier_sleeping: float = 0.15
    fitbit_monitor_path: str = ""
    source_scorer_enabled: bool = False
    source_scorer_total_budget: int = 60
    source_scorer_min_per_source: int = 2
    source_scorer_max_per_source: int = 20
    source_scorer_cache_path: str = ""
    # 偏好否决门：interest_match 低于阈值时硬拒绝，不进入 compose_message
    # 默认值与 config.example.json 保持一致，避免“软偏好”过于容易放行。
    preference_veto_enabled: bool = True
    preference_interest_veto_threshold: float = 0.4
    # 偏好专项 RAG
    preference_retrieval_enabled: bool = True
    preference_top_k: int = 4
    preference_per_source_top_k: int = 2
    preference_max_sources: int = 5
    preference_hyde_enabled: bool = False
    preference_hyde_timeout_ms: int = 2000
    judge_weight_urgency: float = 0.15
    judge_weight_balance: float = 0.10
    judge_weight_dynamics: float = 0.10
    judge_weight_information_gap: float = 0.25
    judge_weight_relevance: float = 0.20
    judge_weight_expected_impact: float = 0.20
    judge_urgency_horizon_hours: float = 12.0
    judge_balance_daily_max: int = 8
    judge_veto_balance_min: float = 0.1
    judge_veto_urgency_min: float = 0.05
    judge_veto_llm_dim_min: int = 2
    judge_send_threshold: float = 0.60
    bg_context_main_topic_min_interval_hours: int = 6
