"""Stable public names for independently owned prompt sections."""

RETRIEVED_MEMORY_SECTION = "memory"
SELF_PROFILE_SECTION = "self_model"
LONG_TERM_PROFILE_SECTION = "long_term_memory"

MARKDOWN_PROFILE_SECTIONS = frozenset(
    {SELF_PROFILE_SECTION, LONG_TERM_PROFILE_SECTION}
)
ALL_MEMORY_SECTIONS = frozenset(
    {RETRIEVED_MEMORY_SECTION, *MARKDOWN_PROFILE_SECTIONS}
)

__all__ = [
    "ALL_MEMORY_SECTIONS",
    "LONG_TERM_PROFILE_SECTION",
    "MARKDOWN_PROFILE_SECTIONS",
    "RETRIEVED_MEMORY_SECTION",
    "SELF_PROFILE_SECTION",
]
