# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.host_bridge import host_bridge_pb2 as agent_dot_host__bridge_dot_host__bridge__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/host_bridge/host_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostBridgeStub(object):
    """单一 release 内的私有主机协议；认证 token 只通过 metadata 传输。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inspect = channel.unary_unary(
                '/akashic.host.v2.HostBridge/Inspect',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.IdentityReply.FromString,
                _registered_method=True)
        self.ClaimBoot = channel.unary_unary(
                '/akashic.host.v2.HostBridge/ClaimBoot',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ClaimBootReply.FromString,
                _registered_method=True)
        self.Probe = channel.unary_unary(
                '/akashic.host.v2.HostBridge/Probe',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.IdentityReply.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/akashic.host.v2.HostBridge/Heartbeat',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/akashic.host.v2.HostBridge/Exec',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ExecRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ExecutionReply.FromString,
                _registered_method=True)
        self.WriteStdin = channel.unary_unary(
                '/akashic.host.v2.HostBridge/WriteStdin',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.WriteStdinRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ExecutionReply.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/akashic.host.v2.HostBridge/Stop',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.StopRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.StopReply.FromString,
                _registered_method=True)
        self.TerminateOwner = channel.unary_unary(
                '/akashic.host.v2.HostBridge/TerminateOwner',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.OwnerRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.CleanupReply.FromString,
                _registered_method=True)
        self.ShutdownManager = channel.unary_unary(
                '/akashic.host.v2.HostBridge/ShutdownManager',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.CleanupReply.FromString,
                _registered_method=True)
        self.ActiveExecutions = channel.unary_unary(
                '/akashic.host.v2.HostBridge/ActiveExecutions',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ActiveExecutionsReply.FromString,
                _registered_method=True)
        self.FileTool = channel.unary_unary(
                '/akashic.host.v2.HostBridge/FileTool',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.FileRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.FileReply.FromString,
                _registered_method=True)
        self.SkillRequirements = channel.unary_unary(
                '/akashic.host.v2.HostBridge/SkillRequirements',
                request_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.SkillRequirementsRequest.SerializeToString,
                response_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.SkillRequirementsReply.FromString,
                _registered_method=True)


class HostBridgeServicer(object):
    """单一 release 内的私有主机协议；认证 token 只通过 metadata 传输。
    """

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimBoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Probe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteStdin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownManager(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkillRequirements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.IdentityReply.SerializeToString,
            ),
            'ClaimBoot': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimBoot,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ClaimBootReply.SerializeToString,
            ),
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.IdentityReply.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.HeartbeatReply.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ExecRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ExecutionReply.SerializeToString,
            ),
            'WriteStdin': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteStdin,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.WriteStdinRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ExecutionReply.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.StopRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.StopReply.SerializeToString,
            ),
            'TerminateOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateOwner,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.OwnerRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.CleanupReply.SerializeToString,
            ),
            'ShutdownManager': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownManager,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.CleanupReply.SerializeToString,
            ),
            'ActiveExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveExecutions,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.ActiveExecutionsReply.SerializeToString,
            ),
            'FileTool': grpc.unary_unary_rpc_method_handler(
                    servicer.FileTool,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.FileRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.FileReply.SerializeToString,
            ),
            'SkillRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.SkillRequirements,
                    request_deserializer=agent_dot_host__bridge_dot_host__bridge__pb2.SkillRequirementsRequest.FromString,
                    response_serializer=agent_dot_host__bridge_dot_host__bridge__pb2.SkillRequirementsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akashic.host.v2.HostBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akashic.host.v2.HostBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostBridge(object):
    """单一 release 内的私有主机协议；认证 token 只通过 metadata 传输。
    """

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/Inspect',
            agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.IdentityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimBoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/ClaimBoot',
            agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.ClaimBootReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/Probe',
            agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.IdentityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/Heartbeat',
            agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/Exec',
            agent_dot_host__bridge_dot_host__bridge__pb2.ExecRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.ExecutionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteStdin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/WriteStdin',
            agent_dot_host__bridge_dot_host__bridge__pb2.WriteStdinRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.ExecutionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/Stop',
            agent_dot_host__bridge_dot_host__bridge__pb2.StopRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.StopReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/TerminateOwner',
            agent_dot_host__bridge_dot_host__bridge__pb2.OwnerRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.CleanupReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShutdownManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/ShutdownManager',
            agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.CleanupReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActiveExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/ActiveExecutions',
            agent_dot_host__bridge_dot_host__bridge__pb2.ContextRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.ActiveExecutionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/FileTool',
            agent_dot_host__bridge_dot_host__bridge__pb2.FileRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.FileReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkillRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akashic.host.v2.HostBridge/SkillRequirements',
            agent_dot_host__bridge_dot_host__bridge__pb2.SkillRequirementsRequest.SerializeToString,
            agent_dot_host__bridge_dot_host__bridge__pb2.SkillRequirementsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
